### ISSUE TITLE
The asset 'hotwire_spark.js' was not found in the load path

### ISSUE THREAD

**Issue by atstockland** [hotwired/spark#61]
Hi!  I don't have much information to add beyond the title.  I installed the gem, hit refresh, and got the following error:

`The asset 'hotwire_spark.js' was not found in the load path`

The console give slightly more:

`Propshaft::MissingAssetError - The asset 'hotwire_spark.js' was not found in the load path.:`

I'm not altering load_path in application.js.  Not sure why else it wouldn't see hotwire_spark.js

Thanks

**Comment by mattmenefee** [comment]
@atstockland can you test whether #65 fixing your issue?

**Comment by atstockland** [comment]
Unfortunately, no.  Same same.

<img width="1510" alt="image" src="https://github.com/user-attachments/assets/0f838efd-e295-48c8-8d51-963036e8ca64" />

**Comment by atstockland** [comment]
@mattmenefee were you able to still reproduce this?  I don't think it's my configuration but I'm open to that possibility.

**Comment by mattmenefee** [comment]
@atstockland yes, I'm still having this issue, but #65 fixes it for me because I have a model in my app named `Asset` which conflicts with using the `asset_path` helper to locate the `hotwire_spark.js` file.

I haven't switched to using Propshaft yet, so I'm not sure if that's the culprit regarding your issue or if it's something else. Sorry I couldn't help any further!

**Comment by atstockland** [comment]
> [@atstockland](https://github.com/atstockland) can you test whether [#65](https://github.com/hotwired/spark/pull/65) fixes your issue?

I'm using esbuild.  I don't have Asset.rb model or resources :assets in my route file.  My initializers/assets.rb file simply has:

`Rails.application.config.assets.version = '1.0'`

As far as I can tell, #65 doesn't help me fix it.

Thanks!  I'll keep trying to figure it out.

**Comment by jorgemanrubia** [comment]
Nice @mattmenefee. I'll merge https://github.com/hotwired/spark/pull/65 if you rebase. Thanks a lot 🙏

**Comment by jorgemanrubia** [comment]
Should be fixed in 0.1.13. Thanks again @mattmenefee!

**Comment by atstockland** [comment]
Still getting the same error:

`Propshaft::MissingAssetError - The asset 'hotwire_spark.js' was not found in the load path.:`

**Comment by atstockland** [comment]
I created a new app, and Hotwire-spark functions correctly.  But, adding it to my existing rails app (currently rails 8, but has been upgraded continually since rails 2)--it fails with the above error.  I'll troubleshoot a bit more.

**Comment by createdbypete** [comment]
A colleague experienced similar @atstockland and running `bin/rails assets:clobber` appeared to sort it out for them if that happens to help out your situation.

**Comment by atstockland** [comment]
@createdbypete Thanks!  That actually did work.  I had to clobber, install the gem, precompile, start the server.  I can see Hotwire-spark is streaming now and no more error.  But for some reason it's not updating the page when I make changes.  I'll solve that issue another day.

Thanks for sharing!  I had given up.

**Comment by jaykilleen** [comment]
Today I upgraded from rails 7.2.2.1 to rails 8.0.1.

Had this same issue and I did the clobber, precompile and restart of the server. Problem solved :)

Really loved seeing this working. It brought me joy 💯 

I hope my experience helps others who might be googling this problem. All the best!

**Comment by minseokchoi00** [comment]
I am using Rails 8.0.2.
When I precompile static assets in the public/assets folder using assets:clobber and assets:precompile, Hotwire Spark's hot-reloading does not work properly.
In the development environment, Hotwire Spark should function correctly if you delete the public/assets folder and do not precompile assets.
